---
deployment:
  tasks:
    - export DEPLOYPATH=/home/develako/public_html

    - /bin/cp -R assets $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R partials $DEPLOYPATH/
    - /bin/cp -R case-studies $DEPLOYPATH/

    - /bin/cp *.php $DEPLOYPATH/
    - /bin/cp *.html $DEPLOYPATH/
    - /bin/cp *.xml $DEPLOYPATH/
    - /bin/cp *.txt $DEPLOYPATH/

    - /bin/cp .htaccess $DEPLOYPATH/
